name       : subversion
version    : 1.9.3
release    : 1
source     :
    - http://www.nic.funet.fi/pub/mirrors/apache.org/subversion/subversion-1.9.3.tar.bz2 : 8bbf6bb125003d88ee1c22935a36b7b1ab7d957e0c8b5fbfe5cb6310b6e86ae0
license    : GPL-2.0 # CHECK ME
summary    : PLEASE FILL ME IN
description: |
    PLEASE FILL ME IN
builddeps  :
    - pkgconfig(apr-1)
    - pkgconfig(apr-util-1)
    - pkgconfig(dbus-1)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(libsasl2)
    - pkgconfig(openssl)
    - pkgconfig(python-2.7)
    - pkgconfig(sqlite3)
    - pkgconfig(zlib)
setup      : |
    %configure --disable-static \
        --with-apr=/usr \
        --with-apr-util=/usr
build      : |
    %make
install    : |
    %make_install
