name       : subversion
version    : 1.9.4
release    : 5
source     :
    - http://www.nic.funet.fi/pub/mirrors/apache.org/subversion/subversion-1.9.4.tar.bz2 : 1267f9e2ab983f260623bee841e6c9cc458bf4bf776238ed5f100983f79e9299
license    : Apache-2.0
summary    : Subversion is an open source version control system
description: |
    Subversion is an open source version control system
component  : programming.tools
builddeps  :
    - pkgconfig(apr-1)
    - pkgconfig(apr-util-1)
    - pkgconfig(bash-completion)
    - pkgconfig(dbus-1)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(libsasl2)
    - pkgconfig(openssl)
    - pkgconfig(serf-1)
    - pkgconfig(sqlite3)
    - pkgconfig(zlib)
    - libtool
    - perl
setup      : |
    %patch -Np0 < $pkgfiles/subversion-1.8.1-revert_bdb6check.patch
    %patch -Np0 < $pkgfiles/subversion.rpath.fix.patch

    %configure --disable-static \
        --with-apr=/usr \
        --with-apr-util=/usr \
        --disable-gmock \
        --disable-disallowing-of-undefined-references \
        --disable-experimental-libtool \
        --with-gnome-keyring \
        --with-serf=/usr \
        --with-sqlite=/usr \
        --with-zlib=/usr
build      : |
    %make
install    : |
    make DESTDIR=$installdir local-install
    install -dm755 $installdir/usr/share/subversion
    cp -a tools/hook-scripts $installdir/usr/share/subversion/
    rm $installdir/usr/share/subversion/hook-scripts/*.in
    install -Dm 644 $pkgfiles/svnserve.service  $installdir/usr/lib/systemd/system/svnserve.service
    install -Dm 644 $pkgfiles/svnserve.conf $installdir/etc/conf.d/svnserve
    install -Dm 644 tools/client-side/bash_completion $installdir/usr/share/bash-completion/completions/subversion
