name       : subversion
version    : 1.10.2
release    : 13
source     :
    - https://www.apache.org/dist/subversion/subversion-1.10.2.tar.bz2 : 5b35e3a858d948de9e8892bf494893c9f7886782f6abbe166c0487c19cf6ed88
license    : Apache-2.0
component  : programming.tools
summary    : Subversion is an open source version control system
description: |
    Subversion is an open source version control system
builddeps  :
    - pkgconfig(apr-1)
    - pkgconfig(apr-util-1)
    - pkgconfig(bash-completion)
    - pkgconfig(dbus-1)
    - pkgconfig(liblz4)
    - pkgconfig(libsasl2)
    - pkgconfig(libsecret-1)
    - pkgconfig(openssl)
    - pkgconfig(serf-1)
    - pkgconfig(sqlite3)
    - pkgconfig(zlib)
    - libtool
    - perl
    - swig
setup      : |
    %patch -Np0 < $pkgfiles/subversion-1.8.1-revert_bdb6check.patch
    %patch -Np0 < $pkgfiles/subversion.rpath.fix.patch

    %configure --disable-static \
        --with-apr=/usr \
        --with-apr-util=/usr \
        --disable-disallowing-of-undefined-references \
        --disable-experimental-libtool \
        --with-gnome-keyring \
        --with-serf=/usr \
        --with-sqlite=/usr \
        --with-zlib=/usr \
        --with-lz4=/usr \
        --with-utf8proc=internal \
        --with-swig
build      : |
    unset LD_AS_NEEDED
    %make
    %make swig-pl swig-pl-lib
install    : |
    unset LD_AS_NEEDED
    make DESTDIR=$installdir local-install install-swig-pl-lib
    make pure_vendor_install -C subversion/bindings/swig/perl/native PERL_INSTALL_ROOT=$installdir
    install -dm 00755 $installdir/usr/share/subversion
    cp -a tools/hook-scripts $installdir/usr/share/subversion/
    rm $installdir/usr/share/subversion/hook-scripts/*.in
    install -Dm 00644 $pkgfiles/svnserve.service  $installdir/usr/lib/systemd/system/svnserve.service
    install -Dm 00644 $pkgfiles/svnserve.conf $installdir/etc/conf.d/svnserve
    install -Dm 00644 tools/client-side/bash_completion $installdir/usr/share/bash-completion/completions/subversion

