name       : subversion
version    : 1.9.7
release    : 11
source     :
    - http://www.nic.funet.fi/pub/mirrors/apache.org/subversion/subversion-1.9.7.tar.bz2 : c3b118333ce12e501d509e66bb0a47bcc34d053990acab45559431ac3e491623
license    : Apache-2.0
component  : programming.tools
summary    : Subversion is an open source version control system
description: |
    Subversion is an open source version control system
builddeps  :
    - pkgconfig(apr-1)
    - pkgconfig(apr-util-1)
    - pkgconfig(bash-completion)
    - pkgconfig(dbus-1)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(libsasl2)
    - pkgconfig(openssl)
    - pkgconfig(serf-1)
    - pkgconfig(sqlite3)
    - pkgconfig(zlib)
    - libtool
    - perl
    - swig
setup      : |
    %patch -Np0 < $pkgfiles/subversion-1.8.1-revert_bdb6check.patch
    %patch -Np0 < $pkgfiles/subversion.rpath.fix.patch
    ./autogen.sh

    %configure --disable-static \
        --with-apr=/usr \
        --with-apr-util=/usr \
        --disable-gmock \
        --disable-disallowing-of-undefined-references \
        --disable-experimental-libtool \
        --with-gnome-keyring \
        --with-serf=/usr \
        --with-sqlite=/usr \
        --with-zlib=/usr \
        --with-swig
build      : |
    unset LD_AS_NEEDED
    %make
    %make swig-pl swig-pl-lib
install    : |
    unset LD_AS_NEEDED
    make DESTDIR=$installdir local-install install-swig-pl-lib
    make pure_vendor_install -C subversion/bindings/swig/perl/native PERL_INSTALL_ROOT=$installdir
    install -dm 00755 $installdir/usr/share/subversion
    cp -a tools/hook-scripts $installdir/usr/share/subversion/
    rm $installdir/usr/share/subversion/hook-scripts/*.in
    install -Dm 00644 $pkgfiles/svnserve.service  $installdir/usr/lib/systemd/system/svnserve.service
    install -Dm 00644 $pkgfiles/svnserve.conf $installdir/etc/conf.d/svnserve
    install -Dm 00644 tools/client-side/bash_completion $installdir/usr/share/bash-completion/completions/subversion

